title: PharmacyIndex
description: Index for Pharmacy students, Med students, and Dentist students
theme: just-the-docs

url: https://isthatadeveloper.github.io/PharmacyIndex.github.io

aux_links:
  Template Repository: https://isthatadeveloper.github.io/PharmacyIndex.github.io

plugins:
  - jekyll-default-layout
